# Generated by Django 4.1.4 on 2022-12-13 11:09

import django.core.validators
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('article', models.CharField(max_length=100, unique=True, verbose_name='Артикул')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Цена')),
                ('status', models.CharField(choices=[(1, 'В наличии'), (2, 'Под заказ'), (3, 'Ожидается поступление'), (4, 'Нет в наличии'), (5, 'Не производится')], max_length=50, verbose_name='Статус')),
                ('image', models.ImageField(upload_to=products.models.get_image_pass, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
